import type { Metadata } from "next";
import '@/app/ui/globals.css';
import { inter, assistant } from '@/app/ui/fonts';
import Header from "./ui/header";



export const metadata: Metadata = {
  title: "Mahsavot Tovot",
  description: "Generated by Mahsavot Tovot app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={assistant.className}>
        <Header></Header>
        {children}
      </body>
    </html>
  );
}
